### ISSUE TITLE
Game files

### ISSUE THREAD

**Issue by d47081** [noodlecollie/nightfire-open#59]
Is the game files included to the project or I must to download it somewhere else (like half-life / valve folder)

Thanks for your work!

**Comment by noodlecollie** [comment]
The game files should be included, yes. You'll need to make sure you have Git LFS installed before you clone the repo. Building the `install` target will copy the game files alongside the binaries, so you should just be able to run the game from there.

**Comment by noodlecollie** [comment]
Nothing on Steam, but you can download pre-built binaries from the releases section of this project's GitHub page.
