### ISSUE TITLE
Build error on Debian 12

### ISSUE THREAD

**Issue by d47081** [noodlecollie/nightfire-open#60]
I have following error on step:

`cmake --build build --config Debug --target install`

```
[ 30%] Building C object xash3d_engine/engine/CMakeFiles/engine.dir/src/server/sv_game.c.o
In function ‘SV_InitEdict’,
    inlined from ‘SV_AllocEdict’ at /home/game/Apps/nightfire-open/xash3d_engine/engine/src/server/sv_game.c:1218:2:
/home/game/Apps/nightfire-open/xash3d_engine/engine/src/server/sv_game.c:1142:9: error: ‘memset’ offset [0, 735] is out of the bounds [0, 0] [-Werror=array-bounds]
 1142 |         memset(&pEdict->v, 0, sizeof(entvars_t));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
gmake[2]: *** [xash3d_engine/engine/CMakeFiles/engine.dir/build.make:1014: xash3d_engine/engine/CMakeFiles/engine.dir/src/server/sv_game.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1267: xash3d_engine/engine/CMakeFiles/engine.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

**Comment by noodlecollie** [comment]
Oh, this is a weird one I remember seeing before but never worked out exactly what was going on. It seemed to change based on other modifications I'd made, and what compiler I was using. I'm on holiday until mid next week, but can try and check it out after that.

**Comment by noodlecollie** [comment]
Nope, this is a hard fork, with a higher warning level than Xash3D. You can also set `-DNF_WARNINGS_AS_ERRORS=OFF` on the CMake command line to allow building even if that strange warning is thrown.

**Comment by noodlecollie** [comment]
Is this still causing an issue? Looking online, it seems it could be a GCC bug related to optimisations. Does it happen in debug builds, or only release builds?

**Comment by noodlecollie** [comment]
I'm going to close this for lack of activity, but if it comes up again then let me know.
